[book]
authors = ["dhruvdh"]
language = "en"
multilingual = false
src = "src"
title = "ni"

[output.html]
default-theme = "light"
mathjax-support = true
git-repository-url = "https://github.com/DhruvDh/ni"
additional-css = ["mermaid.css"]
additional-js = ["mermaid.min.js", "mermaid.init.js"]
google-analytics = "UA-92382442-2" 

[build]
build-dir = "docs"
create-missing = true