[book]
authors = ["dhruvdh"]
language = "en"
multilingual = false
src = "src"
title = "ni"

[output.html]
default-theme = "ayu"
mathjax-support = true

[build]
build-dir = "docs"
create-missing = true